# Generated by Django 4.2.1 on 2023-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='09180000000', max_length=20, unique=True, verbose_name='شماره همراه'),
        ),
    ]
