# Generated by Django 4.2.1 on 2023-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='بدون شماره', max_length=20, unique=True, verbose_name='شماره همراه'),
        ),
    ]
