# Generated by Django 4.2.1 on 2023-10-06 09:29

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_managers_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('receives', 'دریافت\u200cها'), ('payments', 'پرداخت\u200cها'), ('activities', 'فعالیت\u200cها'), ('buyers_sellers', 'خریداران / فروشندگان'), ('orders', 'سفارشات'), ('projects', 'پروژه\u200cها'), ('work_reference', 'ارجاع کار'), ('cheques', 'چک\u200cها'), ('receive_pay', 'دریافت و پرداخت'), ('warehouse_import', 'دریافت و پرداخت'), ('bank_receives', 'رسیدهای بانکی'), ('fund', 'تنخواه')], max_length=30, verbose_name='نوع گزارش')),
                ('date_from', django_jalali.db.models.jDateField(verbose_name='از تاریخ')),
                ('date_to', django_jalali.db.models.jDateField(verbose_name='تا تاریخ')),
                ('report_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان گزارش')),
            ],
            options={
                'verbose_name': 'گزارشات',
            },
        ),
    ]
