# Generated by Django 4.2.1 on 2023-10-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
