# Generated by Django 4.2.1 on 2023-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان پروژه')),
                ('contract_type', models.CharField(choices=[('pc', 'مشارکت در ساخت'), ('ow', 'مالکیت'), ('pa', 'شراکتی'), ('co', 'پیمانی')], max_length=20, verbose_name='نوع قرارداد')),
                ('owners', models.CharField(max_length=100, verbose_name='مالکین')),
                ('contractual_salary', models.BigIntegerField(default=0, verbose_name='دستمزد قرارداد پیمانی')),
                ('contractual_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='درصد قرارداد پیمانی')),
                ('costs_estimation', models.BigIntegerField(default=0, editable=False, verbose_name='برآورد ریالی کل هزینه')),
            ],
        ),
    ]
