# Generated by Django 4.2.1 on 2023-06-18 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_card_image', models.ImageField(upload_to='images/owners', verbose_name='تصویر کارت ملی')),
                ('birth_certificate_image', models.ImageField(upload_to='images/owners', verbose_name='تصویر شناسنامه')),
                ('ownership_document_image', models.ImageField(upload_to='images/owners', verbose_name='تصویر سند مالکیت')),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': 'مالکین',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان پروژه')),
                ('contract_type', models.CharField(choices=[('pc', 'مشارکت در ساخت'), ('ow', 'مالکیت'), ('pa', 'شراکتی'), ('co', 'پیمانی')], max_length=2, verbose_name='نوع قرارداد')),
                ('contractual_salary', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='دستمزد قرارداد پیمانی')),
                ('contractual_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='درصد قرارداد پیمانی')),
                ('owners', models.ManyToManyField(related_name='projects', to='projects.owners', verbose_name='مالکین')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=250, verbose_name='نوع فعالیت')),
                ('referrer', models.CharField(max_length=250, verbose_name='ارجاع دهنده')),
                ('doing_agent', models.CharField(max_length=250, verbose_name='مأمور انجام')),
                ('follow_confirm', models.BooleanField(default=False, verbose_name='تأیید پیگیری')),
                ('follow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیگیری')),
                ('result_explan', models.TextField(default='بدون توضیح')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_work_references', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'ارجاع کار',
                'verbose_name_plural': 'ارجاع کارها',
            },
        ),
        migrations.CreateModel(
            name='ImagesPaymentReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_office', models.ImageField(upload_to='images/payment_receipts', verbose_name='دفتر طراح')),
                ('supervisors', models.ImageField(upload_to='images/payment_receipts', verbose_name='ناظرین')),
                ('engineer_system', models.ImageField(upload_to='images/payment_receipts', verbose_name='نظام مهندسی')),
                ('sketch_map', models.ImageField(upload_to='images/payment_receipts', verbose_name='نقشه کروکی')),
                ('export_permit', models.ImageField(upload_to='images/payment_receipts', verbose_name='عوارض صدور پروانه')),
                ('visit_toll', models.ImageField(upload_to='images/payment_receipts', verbose_name='عوارض بازدید')),
                ('education_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم آموزش و پرورش')),
                ('fire_stations_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم آتشنشانی')),
                ('social_security_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم تأمین اجتماعی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_payment_receipts', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر فیش پرداختی',
                'verbose_name_plural': 'تصاویر فیش های پرداختی',
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب آب')),
                ('electricity_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب برق')),
                ('gas_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب گاز')),
                ('phone_subscription', models.PositiveIntegerField(default=0, verbose_name='هزینه اشتراک تلفن')),
                ('designer_office', models.PositiveIntegerField(default=0, verbose_name='هزینه دفتر طراح')),
                ('supervisors', models.PositiveIntegerField(default=0, verbose_name='هزینه ناظرین')),
                ('engineer_system', models.PositiveIntegerField(default=0, verbose_name='هزینه نظام مهندسی')),
                ('sketch_map', models.PositiveIntegerField(default=0, verbose_name='هزینه نقشه کروکی')),
                ('export_permit', models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پروانه')),
                ('export_end_work', models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پایان کار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_costs', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه ها',
            },
        ),
    ]
