# Generated by Django 4.2.1 on 2023-11-26 04:35

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreference',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workreference',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='follow_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پیگیری'),
        ),
    ]
