# Generated by Django 4.2.1 on 2023-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_type',
            field=models.CharField(choices=[('pc', 'مشارکت در ساخت'), ('ow', 'مالکیت'), ('pa', 'شراکتی'), ('co', 'پیمانی')], max_length=2, verbose_name='نوع قرارداد'),
        ),
    ]
