# Generated by Django 4.2.1 on 2023-07-04 06:29

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreference',
            name='follow_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیگیری'),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='result_explan',
            field=models.TextField(),
        ),
    ]
