# Generated by Django 4.2.1 on 2023-11-26 05:25

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_workreference_create_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreference',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workreference',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
