# Generated by Django 4.2.1 on 2023-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_card_image', models.ImageField(upload_to='images', verbose_name='تصویر کارت ملی')),
                ('birth_certificate_image', models.ImageField(upload_to='images', verbose_name='تصویر شناسنامه')),
                ('ownership_document_image', models.ImageField(upload_to='images', verbose_name='تصویر سند مالکیت')),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': 'مالکین',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='owners',
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(related_name='projects', to='projects.owners', verbose_name='مالکین'),
        ),
    ]
