# Generated by Django 4.2.1 on 2023-07-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_imagespaymentreceipts_paymentsimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='sketch_map',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه تهیه نقشه کروکی'),
        ),
    ]
