# Generated by Django 4.2.1 on 2023-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_owners_remove_project_owners_project_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='birth_certificate_image',
            field=models.ImageField(upload_to='images/owners', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='national_card_image',
            field=models.ImageField(upload_to='images/owners', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='ownership_document_image',
            field=models.ImageField(upload_to='images/owners', verbose_name='تصویر سند مالکیت'),
        ),
    ]
