# Generated by Django 4.2.1 on 2023-11-26 11:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_costs_create_record_costs_update_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='costs',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentsimages',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentsimages',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
