# Generated by Django 4.2.1 on 2023-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractual_salary',
            field=models.PositiveBigIntegerField(default=0, verbose_name='دستمزد قرارداد پیمانی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_estimation',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='برآورد ریالی کل هزینه'),
        ),
    ]
