# Generated by Django 4.2.1 on 2023-05-19 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_contractual_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=250, verbose_name='نوع فعالیت')),
                ('referrer', models.CharField(max_length=250, verbose_name='ارجاع دهنده')),
                ('doing_agent', models.CharField(max_length=250, verbose_name='مأمور انجام')),
                ('follow_confirm', models.BooleanField(default=False, verbose_name='تأیید پیگیری')),
                ('follow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیگیری')),
                ('result_explan', models.TextField(default='بدون توضیح')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_work_references', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'ارجاع کار',
                'verbose_name_plural': 'ارجاع کارها',
            },
        ),
    ]
