# Generated by Django 4.2.1 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_paymentsimages_designer_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='birth_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/owners/birth_certificates', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/owners/national_cards', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='ownership_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/owners/ownership_documents', verbose_name='تصویر سند مالکیت'),
        ),
    ]
