# Generated by Django 4.2.1 on 2023-05-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_workreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب آب')),
                ('electricity_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب برق')),
                ('gas_branch', models.PositiveIntegerField(default=0, verbose_name='هزینه انشعاب گاز')),
                ('phone_subscription', models.PositiveIntegerField(default=0, verbose_name='هزینه اشتراک تلفن')),
                ('designer_office', models.PositiveIntegerField(default=0, verbose_name='هزینه دفتر طراح')),
                ('supervisors', models.PositiveIntegerField(default=0, verbose_name='هزینه ناظرین')),
                ('engineer_system', models.PositiveIntegerField(default=0, verbose_name='هزینه نظام مهندسی')),
                ('sketch_map', models.PositiveIntegerField(default=0, verbose_name='هزینه نقشه کروکی')),
                ('export_permit', models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پروانه')),
                ('export_end_work', models.PositiveIntegerField(default=0, verbose_name='هزینه صدور پایان کار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_costs', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه ها',
            },
        ),
    ]
