# Generated by Django 4.2.1 on 2023-05-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPaymentReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_office', models.ImageField(upload_to='images/payment_receipts', verbose_name='دفتر طراح')),
                ('supervisors', models.ImageField(upload_to='images/payment_receipts', verbose_name='ناظرین')),
                ('engineer_system', models.ImageField(upload_to='images/payment_receipts', verbose_name='نظام مهندسی')),
                ('sketch_map', models.ImageField(upload_to='images/payment_receipts', verbose_name='نقشه کروکی')),
                ('export_permit', models.ImageField(upload_to='images/payment_receipts', verbose_name='عوارض صدور پروانه')),
                ('visit_toll', models.ImageField(upload_to='images/payment_receipts', verbose_name='عوارض بازدید')),
                ('education_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم آموزش و پرورش')),
                ('fire_stations_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم آتشنشانی')),
                ('social_security_share', models.ImageField(upload_to='images/payment_receipts', verbose_name='سهم تأمین اجتماعی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_payment_receipts', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر فیش پرداختی',
                'verbose_name_plural': 'تصاویر فیش های پرداختی',
            },
        ),
    ]
