# Generated by Django 4.2.1 on 2023-06-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_costs_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractual_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='درصد قرارداد پیمانی'),
        ),
    ]
