# Generated by Django 4.2.1 on 2023-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_contractual_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractual_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='درصد قرارداد پیمانی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractual_salary',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='دستمزد قرارداد پیمانی'),
        ),
    ]
