# Generated by Django 4.2.1 on 2023-11-04 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('non_government_accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_type', models.CharField(max_length=100, verbose_name='نوع کالا')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='UseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('is_deficient', models.BooleanField(default=False, verbose_name='کسری دارد')),
                ('deficient_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مقدار کسری')),
                ('is_excess', models.BooleanField(default=False, verbose_name='مازاد دارد')),
                ('excess_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مقدار مازاد')),
                ('start_using_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع مصرف')),
                ('finish_using_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان مصرف')),
                ('returned_to', models.CharField(blank=True, choices=[('prw', 'انبار پروژه'), ('maw', 'انبار اصلی')], max_length=3, null=True, verbose_name='مرجوعی به')),
                ('return_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارجاع به انبار')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_certificate_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'گواهی مصرف کالا',
                'verbose_name_plural': 'گواهی\u200cهای مصرف کالا',
            },
        ),
        migrations.CreateModel(
            name='ProjectWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('status', models.CharField(choices=[('exp', 'خروج از انبار'), ('imp', 'ورود به انبار')], max_length=3, verbose_name='وضعیت')),
                ('contractor_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_contractors_applies', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('contractor_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_contractors_deliveries', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('personnel_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_personnel_applies', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('personnel_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_personnel_deliveries', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_projects', to='projects.project', verbose_name='پروژه')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
                ('use_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_use_certificates', to='warehousing.usecertificate', verbose_name='گواهی مصرف')),
            ],
            options={
                'verbose_name': 'کالای انبار پروژه',
                'verbose_name_plural': 'کالاهای انبار پروژه',
            },
        ),
        migrations.CreateModel(
            name='MainWarehouseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_sender', models.TextField(blank=True, null=True, verbose_name='سایر')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('date_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('is_returned', models.BooleanField(default=False, verbose_name='کالا مرجوعی است')),
                ('project_returned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_returned_projects', to='projects.project', verbose_name='مرجوعی از پروژه')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_personnel', to='non_government_accounts.personnel', verbose_name='تحویل گیرنده')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_suppliers', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'کالای افزوده شده به انبار',
                'verbose_name_plural': 'کالاهای افزوده شده به انبار',
            },
        ),
        migrations.CreateModel(
            name='MainWarehouseExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_contractors', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_deliverers', to='non_government_accounts.personnel', verbose_name='تحویل دهنده')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_personnel', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_projects', to='projects.project', verbose_name='پروژه')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'کالای خارج شده از انبار',
                'verbose_name_plural': 'کالاهای خارج شده از انبار',
            },
        ),
    ]
