# Generated by Django 4.2.1 on 2023-07-20 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0012_alter_orders_supplier'),
        ('projects', '0004_alter_costs_sketch_map'),
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWarehouseImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_sender', models.TextField(blank=True, null=True, verbose_name='سایر')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('date_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('is_returned', models.BooleanField(default=False, verbose_name='مرجوعی')),
                ('project_returned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_returned_projects', to='projects.project', verbose_name='مرجوعی از پروژه')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_personnel', to='non_government_accounts.personnel', verbose_name='تحویل گیرنده')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_import_suppliers', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'کالای افزوده شده به انبار',
                'verbose_name_plural': 'کالاهای افزوده شده به انبار',
            },
        ),
    ]
