# Generated by Django 4.2.1 on 2023-12-01 10:15

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainwarehouseimport',
            name='date_time',
        ),
        migrations.AddField(
            model_name='mainwarehouseexport',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mainwarehouseexport',
            name='export_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ خروج کالا'),
        ),
        migrations.AddField(
            model_name='mainwarehouseexport',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mainwarehouseimport',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mainwarehouseimport',
            name='import_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ ورود کالا'),
        ),
        migrations.AddField(
            model_name='mainwarehouseimport',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectwarehouse',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectwarehouse',
            name='export_import_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ ورود/خروج'),
        ),
        migrations.AddField(
            model_name='projectwarehouse',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usecertificate',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usecertificate',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
