# Generated by Django 4.2.1 on 2023-12-01 10:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0002_remove_mainwarehouseimport_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwarehouseexport',
            name='export_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ خروج کالا'),
        ),
        migrations.AlterField(
            model_name='mainwarehouseimport',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainwarehouseimport',
            name='import_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ورود کالا'),
        ),
        migrations.AlterField(
            model_name='mainwarehouseimport',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectwarehouse',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectwarehouse',
            name='export_import_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ورود/خروج'),
        ),
        migrations.AlterField(
            model_name='projectwarehouse',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usecertificate',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usecertificate',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
