# Generated by Django 4.2.1 on 2023-07-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_costs_sketch_map'),
        ('non_government_accounts', '0012_alter_orders_supplier'),
        ('warehousing', '0002_mainwarehouseimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwarehouseimport',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='کالا مرجوعی است'),
        ),
        migrations.CreateModel(
            name='MainWarehouseExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_contractors', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_deliverers', to='non_government_accounts.personnel', verbose_name='تحویل دهنده')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_personnel', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_projects', to='projects.project', verbose_name='پروژه')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_export_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'کالای خارج شده از انبار',
                'verbose_name_plural': 'کالاهای خارج شده از انبار',
            },
        ),
    ]
