# Generated by Django 4.2.1 on 2023-07-23 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0003_alter_mainwarehouseimport_is_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('is_deficient', models.BooleanField(default=False, verbose_name='کسری دارد')),
                ('deficient_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مقدار کسری')),
                ('is_excess', models.BooleanField(default=False, verbose_name='مازاد دارد')),
                ('excess_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مقدار مازاد')),
                ('start_using_date', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع مصرف')),
                ('finish_using_date', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پایان مصرف')),
                ('returned_to', models.CharField(blank=True, choices=[('prw', 'انبار پروژه'), ('maw', 'انبار اصلی')], max_length=3, null=True, verbose_name='مرجوعی به')),
                ('return_date', django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ارجاع به انبار')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_certificate_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'گواهی مصرف کالا',
                'verbose_name_plural': 'گواهی\u200cهای مصرف کالا',
            },
        ),
    ]
