# Generated by Django 4.2.1 on 2023-12-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0003_alter_mainwarehouseexport_export_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainwarehouseexport',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='mainwarehouseimport',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='projectwarehouse',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='usecertificate',
            name='measurement_unit',
        ),
    ]
