# Generated by Django 4.2.1 on 2023-07-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0012_alter_orders_supplier'),
        ('projects', '0004_alter_costs_sketch_map'),
        ('warehousing', '0004_usecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('stuff_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('status', models.CharField(choices=[('exp', 'خروج از انبار'), ('imp', 'ورود به انبار')], max_length=3, verbose_name='وضعیت')),
                ('contractor_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_contractors_applies', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('contractor_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_contractors_deliveries', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('personnel_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_personnel_applies', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('personnel_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_personnel_deliveries', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_projects', to='projects.project', verbose_name='پروژه')),
                ('stuff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_stuffs', to='warehousing.stuff', verbose_name='نوع کالا')),
                ('use_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_warehouse_use_certificates', to='warehousing.usecertificate', verbose_name='گواهی مصرف')),
            ],
            options={
                'verbose_name': 'کالای انبار پروژه',
                'verbose_name_plural': 'کالاهای انبار پروژه',
            },
        ),
    ]
