# Generated by Django 4.2.1 on 2023-12-04 17:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0004_remove_mainwarehouseexport_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwarehouseexport',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainwarehouseexport',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
