# Generated by Django 4.2.1 on 2023-12-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_costs_create_record_alter_costs_update_record_and_more'),
        ('warehousing', '0006_usecertificate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecertificate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_certificate_projects', to='projects.project', verbose_name='پروژه'),
        ),
    ]
