# Generated by Django 4.2.1 on 2023-12-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0007_alter_usecertificate_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwarehouse',
            name='use_certificate',
        ),
    ]
