# Generated by Django 4.2.1 on 2023-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0008_remove_projectwarehouse_use_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='measurement_unit',
            field=models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد'), ('bag', 'کیسه')], max_length=3, verbose_name='واحد اندازه گیری'),
        ),
    ]
