# Generated by Django 4.2.1 on 2023-05-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='نام پیمانکار')),
                ('lastname', models.CharField(max_length=150, verbose_name='نام خانوادگی پیمانکار')),
                ('job', models.CharField(max_length=150, verbose_name='رشته شغلی پیمانکار')),
                ('phone', models.CharField(max_length=150, verbose_name='شماره تماس پیمانکار')),
                ('address', models.TextField(max_length=150, verbose_name='آدرس پیمانکار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractors', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
