# Generated by Django 4.2.1 on 2023-11-04 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyersSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_seller', models.CharField(choices=[('buy', 'خریدار'), ('sel', 'فروشنده')], max_length=3, verbose_name='خریدار / فروشنده')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contract_image', models.ImageField(upload_to='images/buyers_sellers', verbose_name='تصویر قرارداد')),
                ('payment_order', models.CharField(choices=[('csh', 'نقدی'), ('chq', 'چک'), ('del', 'حین تحویل'), ('dtr', 'انتقال سند'), ('afh', 'بعد از سفت\u200c کاری'), ('aif', 'بعد از اجرای تأسیسات'), ('atc', 'بعد از کاشی و سرامیک'), ('afc', 'بعد از سقف طبقه'), ('aff', 'بعد از فونداسیون'), ('oth', 'سایر')], max_length=3, verbose_name='ترتیب پرداخت')),
                ('current_roof', models.CharField(blank=True, max_length=50, null=True, verbose_name='سقف کنونی')),
                ('payment_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('payment_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداختی')),
            ],
            options={
                'verbose_name': 'خریدار / فروشنده',
                'verbose_name_plural': 'خریداران / فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='رشته شغلی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contract_image', models.ImageField(upload_to='images/personnel', verbose_name='تصویر قرارداد')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='رشته شغلی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_suppliers', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تأمین کننده',
                'verbose_name_plural': 'تأمین کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ سرمایه\u200cگذاری')),
                ('contract_image', models.ImageField(upload_to='images/partners', verbose_name='تصویر قرارداد')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'شریک',
                'verbose_name_plural': 'شرکاء',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100, verbose_name='نوع سفارش')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن'), ('num', 'عدد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد')),
                ('order_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار سفارش')),
                ('order_total_price', models.PositiveBigIntegerField(default=0, editable=False)),
                ('order_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان سفارش')),
                ('order_respite', models.PositiveSmallIntegerField(default=0, verbose_name='مهلت سفارش')),
                ('order_result', models.CharField(choices=[('spd', 'ارسال در تاریخ مشخص'), ('snd', 'ارسال شده'), ('cld', 'لغو شده')], max_length=3, verbose_name='نتیجه سفارش')),
                ('sending_date', django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ارسال')),
                ('sended_image', models.ImageField(blank=True, null=True, upload_to='images/sended_images', verbose_name='تصویر سفارش ارسال شده')),
                ('sended_image_type', models.CharField(blank=True, choices=[('blg', 'بارنامه'), ('fac', 'فاکتور'), ('enf', 'برگه ورود'), ('exf', 'برگه خروج')], max_length=3, null=True, verbose_name='نوع تصویر سفارش ارسال شده')),
                ('explan_order_cancel', models.TextField(blank=True, null=True, verbose_name='توضیح علت لغو سفارش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_orders', to='projects.project', verbose_name='پروژه')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_suppliers', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='رشته شغلی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractors', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'پیمانکار',
                'verbose_name_plural': 'پیمانکاران',
            },
        ),
        migrations.CreateModel(
            name='ConflictOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('pos', 'بیشتر از سفارش'), ('neg', 'کمتر از سفارش')], max_length=3, verbose_name='نوع مغایرت')),
                ('conflict_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار مغایرت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_conflicts', to='non_government_accounts.orders', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مغایرت سفارش',
                'verbose_name_plural': 'مغایرت سفارشات',
            },
        ),
    ]
