# Generated by Django 4.2.1 on 2023-05-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
        ('non_government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='address',
            field=models.TextField(verbose_name='آدرس پیمانکار'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='job',
            field=models.CharField(max_length=100, verbose_name='رشته شغلی پیمانکار'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی پیمانکار'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس پیمانکار'),
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='نام تأمین کننده')),
                ('lastname', models.CharField(max_length=200, verbose_name='نام خانوادگی تأمین کننده')),
                ('job', models.CharField(max_length=100, verbose_name='رشته شغلی تأمین کننده')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس تأمین کننده')),
                ('address', models.TextField(verbose_name='آدرس تأمین کننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_suppliers', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
