# Generated by Django 4.2.1 on 2023-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractors',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contractors',
            name='lastname',
        ),
        migrations.AddField(
            model_name='contractors',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='job',
            field=models.CharField(max_length=100, verbose_name='رشته شغلی'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
