# Generated by Django 4.2.1 on 2023-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0002_alter_contractors_address_alter_contractors_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='نام')),
                ('lastname', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='رشته شغلی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contract_image', models.ImageField(upload_to='images', verbose_name='تصویر قرارداد')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
        migrations.AlterModelOptions(
            name='contractors',
            options={'verbose_name': 'پیمانکار', 'verbose_name_plural': 'پیمانکاران'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'تأمین کننده', 'verbose_name_plural': 'تأمین کنندگان'},
        ),
    ]
