# Generated by Django 4.2.1 on 2023-05-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_and_more'),
        ('non_government_accounts', '0003_personnel_alter_contractors_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_card_image', models.ImageField(upload_to='images', verbose_name='تصویر کارت ملی')),
                ('birth_certificate_image', models.ImageField(upload_to='images', verbose_name='تصویر شناسنامه')),
                ('ownership_document_image', models.ImageField(upload_to='images', verbose_name='تصویر سند مالکیت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owners', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
