# Generated by Django 4.2.1 on 2023-06-25 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0003_remove_personnel_firstname_remove_personnel_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('csh', 'نقدی'), ('chq', 'چک'), ('del', 'حین تحویل'), ('dtr', 'انتقال سند'), ('afh', 'بعد از سفت\u200c کاری'), ('aif', 'بعد از اجرای تأسیسات'), ('atc', 'بعد از کاشی و سرامیک'), ('afc', 'بعد از سقف طبقه'), ('aff', 'بعد از فونداسیون'), ('oth', 'سایر')], max_length=3, verbose_name='نوع ترتیب پرداخت')),
                ('current_roof', models.CharField(blank=True, max_length=50, null=True, verbose_name='سقف کنونی')),
                ('approximate_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تقریبی')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='cash_date',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='cheque_payment',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='delivery_amount',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='delivery_cheque',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='doc_transfer_amount',
        ),
        migrations.RemoveField(
            model_name='buyerssellers',
            name='doc_transfer_cheque',
        ),
        migrations.AddField(
            model_name='buyerssellers',
            name='payment_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AddField(
            model_name='buyerssellers',
            name='payment_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='job',
            field=models.CharField(max_length=100, verbose_name='رشته شغلی'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='buyerssellers',
            name='payment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order_buyers_sellers', to='non_government_accounts.paymentorder', verbose_name='ترتیب پرداخت'),
        ),
    ]
