# Generated by Django 4.2.1 on 2023-05-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0004_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name': 'مالک', 'verbose_name_plural': 'مالکین'},
        ),
    ]
