# Generated by Django 4.2.1 on 2023-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0004_paymentorder_remove_buyerssellers_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerssellers',
            name='current_roof',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سقف کنونی'),
        ),
        migrations.AlterField(
            model_name='buyerssellers',
            name='payment_order',
            field=models.CharField(choices=[('csh', 'نقدی'), ('chq', 'چک'), ('del', 'حین تحویل'), ('dtr', 'انتقال سند'), ('afh', 'بعد از سفت\u200c کاری'), ('aif', 'بعد از اجرای تأسیسات'), ('atc', 'بعد از کاشی و سرامیک'), ('afc', 'بعد از سقف طبقه'), ('aff', 'بعد از فونداسیون'), ('oth', 'سایر')], max_length=3, verbose_name='ترتیب پرداخت'),
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
