# Generated by Django 4.2.1 on 2023-11-19 17:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0004_buyerssellers_create_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerssellers',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buyerssellers',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
