# Generated by Django 4.2.1 on 2023-05-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0005_alter_owners_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
