# Generated by Django 4.2.1 on 2023-11-26 04:35

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0005_alter_buyerssellers_create_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ سفارش'),
        ),
    ]
