# Generated by Django 4.2.1 on 2023-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0006_alter_orders_explan_order_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sended_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sended_images', verbose_name='تصویر سفارش ارسال شده'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sended_image_type',
            field=models.CharField(blank=True, choices=[('blg', 'بارنامه'), ('fac', 'فاکتور'), ('enf', 'برگه ورود'), ('exf', 'برگه خروج')], max_length=3, null=True, verbose_name='نوع تصویر سفارش ارسال شده'),
        ),
    ]
