# Generated by Django 4.2.1 on 2023-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0006_delete_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='contract_image',
            field=models.ImageField(upload_to='images/personnel', verbose_name='تصویر قرارداد'),
        ),
    ]
