# Generated by Django 4.2.1 on 2023-05-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('non_government_accounts', '0007_alter_personnel_contract_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.BigIntegerField(default=0, verbose_name='مبلغ سرمایه\u200cگذاری')),
                ('contract_image', models.ImageField(upload_to='images/partners', verbose_name='تصویر قرارداد')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
