# Generated by Django 4.2.1 on 2023-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0007_alter_orders_sended_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='explan_order_cancel',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح علت لغو سفارش'),
        ),
    ]
