# Generated by Django 4.2.1 on 2023-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0008_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'شریک', 'verbose_name_plural': 'شرکاء'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='investment_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ سرمایه\u200cگذاری'),
        ),
    ]
