# Generated by Django 4.2.1 on 2024-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0008_alter_conflictorders_create_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerssellers',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buyers_sellers', verbose_name='تصویر قرارداد'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/partners', verbose_name='تصویر قرارداد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/personnel', verbose_name='تصویر قرارداد'),
        ),
    ]
