# Generated by Django 4.2.1 on 2023-05-18 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_contractual_salary_and_more'),
        ('non_government_accounts', '0010_buyerssellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='supplier_demand',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100, verbose_name='نوع سفارش')),
                ('measurement_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('num', 'تعداد')], max_length=3, verbose_name='واحد اندازه گیری')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد')),
                ('order_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار سفارش')),
                ('order_total_price', models.PositiveBigIntegerField(default=0, editable=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان سفارش')),
                ('order_respite', models.PositiveSmallIntegerField(default=0, verbose_name='مهلت سفارش')),
                ('order_result', models.CharField(choices=[('spd', 'ارسال در تاریخ مشخص'), ('snd', 'ارسال شده'), ('cld', 'لغو شده')], max_length=3, verbose_name='نتیجه سفارش')),
                ('sending_date', models.DateTimeField(default=django.utils.timezone.now, help_text='ارسال در تاریخ مشخص', verbose_name='تاریخ ارسال')),
                ('sended_image', models.ImageField(upload_to='images/sended_images', verbose_name='تصویر سفارش ارسال شده')),
                ('sended_image_type', models.CharField(choices=[('blg', 'بارنامه'), ('fac', 'فاکتور'), ('enf', 'برگه ورود'), ('exf', 'برگه خروج')], max_length=3, verbose_name='نوع تصویر سفارش ارسال شده')),
                ('explan_order_cancel', models.TextField(default='بدون توضیح')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_orders', to='projects.project', verbose_name='پروژه')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_supliers', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
