# Generated by Django 4.2.1 on 2023-05-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0012_alter_orders_explan_order_cancel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='supplier_demand',
        ),
        migrations.CreateModel(
            name='NoticeConflictOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('pos', 'بیشتر از سفارش'), ('neg', 'کمتر از سفارش')], max_length=3, verbose_name='نوع مغایرت')),
                ('conflict_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار مغایرت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_conflicts', to='non_government_accounts.orders', verbose_name='سفارش')),
            ],
        ),
    ]
