# Generated by Django 4.2.1 on 2024-11-17 17:45

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('non_government_accounts', '0001_initial'),
        ('projects', '0001_initial'),
        ('government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('rem', 'برداشت'), ('set', 'واریز')], max_length=3, verbose_name='نوع عملیات')),
                ('settle_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی')),
                ('settle_image', models.ImageField(blank=True, null=True, upload_to='images/cash_box/settle_images', verbose_name='تصویر فیش واریزی')),
                ('settle_description', models.TextField(blank=True, null=True, verbose_name='شرح واریز')),
                ('settle_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ واریز')),
                ('removal_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ برداشت')),
                ('removal_image', models.ImageField(blank=True, null=True, upload_to='images/cash_box/removal_images', verbose_name='تصویر فیش برداشت')),
                ('removal_description', models.TextField(blank=True, null=True, verbose_name='شرح برداشت')),
                ('removal_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ برداشت')),
                ('create_record', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_record', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('operation_type', models.CharField(choices=[('rem', 'برداشت'), ('set', 'واریز')], max_length=3, verbose_name='نوع عملیات')),
                ('cost_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ هزینه')),
                ('cost_description', models.TextField(blank=True, null=True, verbose_name='شرح هزینه')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='images/fund/receipt_images', verbose_name='تصویر فیش پرداختی')),
                ('removal_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ برداشت')),
                ('charge_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی')),
                ('charge_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ واریز')),
                ('charge_image', models.ImageField(blank=True, null=True, upload_to='images/fund/charge_images', verbose_name='تصویر فیش واریزی')),
                ('create_record', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_record', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه',
            },
        ),
        migrations.CreateModel(
            name='ReceivePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_pay', models.CharField(choices=[('rec', 'دریافت'), ('pay', 'پرداخت')], max_length=3, verbose_name='دریافت / پرداخت')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('regard_to', models.CharField(max_length=100, verbose_name='بابت')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='images/receive_pays', verbose_name='تصویر فیش')),
                ('create_record', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_record', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_receive_pays', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_receive_pays', to='government_accounts.organization', verbose_name='طرف حساب دولتی')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_receive_pays', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_receive_pays', to='projects.project', verbose_name='پروژه')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_receive_pays', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'دریافت و پرداخت',
                'verbose_name_plural': 'دریافت\u200cها و پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_type', models.CharField(choices=[('exp', 'صدور'), ('rec', 'دریافت')], max_length=3, verbose_name='نوع چک')),
                ('cheque_for', models.CharField(max_length=100, verbose_name='بابت')),
                ('cheque_number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('bank_branch', models.CharField(max_length=50, verbose_name='بانک و شعبه')),
                ('cheque_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('registered', models.BooleanField(default=False, verbose_name='ثبت شده')),
                ('cheque_image', models.ImageField(blank=True, null=True, upload_to='images/cheques', verbose_name='تصویر چک')),
                ('export_receive_date', django_jalali.db.models.jDateField(verbose_name='تاریخ صدور / دریافت')),
                ('due_date', django_jalali.db.models.jDateField(verbose_name='تاریخ سررسید')),
                ('account_owner', models.CharField(max_length=250, verbose_name='صاحب حساب')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('create_record', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_record', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cheques', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
            },
        ),
    ]
