# Generated by Django 4.2.1 on 2023-05-18 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_alter_project_contractual_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_type', models.CharField(choices=[('exp', 'صدور'), ('rec', 'دریافت')], max_length=3, verbose_name='نوع چک')),
                ('cheque_for', models.CharField(max_length=100, verbose_name='بابت')),
                ('cheque_number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('bank_branch', models.CharField(max_length=50, verbose_name='بانک و شعبه')),
                ('cheque_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('registered', models.BooleanField(default=False, verbose_name='ثبت شده')),
                ('cheque_image', models.ImageField(upload_to='images/cheques', verbose_name='تصویر چک')),
                ('export_receive_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور / دریافت')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ سررسید')),
                ('account_owner', models.CharField(max_length=250, verbose_name='صاحب حساب')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cheques', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
            },
        ),
    ]
