# Generated by Django 4.2.1 on 2023-05-28 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheques',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
