# Generated by Django 4.2.1 on 2023-11-29 16:38

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cheques',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cheques',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fund',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fund',
            name='removal_date',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ برداشت'),
        ),
        migrations.AddField(
            model_name='fund',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivepay',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivepay',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='due_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='export_receive_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ صدور / دریافت'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
