# Generated by Django 4.2.1 on 2023-07-07 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0011_rename_noticeconflictorders_conflictorders'),
        ('government_accounts', '0001_initial'),
        ('cheques_receive_pay', '0002_alter_cheques_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('cash', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='موجودی')),
                ('cost_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ هزینه')),
                ('cost_description', models.TextField(verbose_name='شرح هزینه')),
                ('receipt_image', models.ImageField(upload_to='images/receive_pays', verbose_name='تصویر فیش پرداختی')),
                ('charge_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('charge_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('charge_image', models.ImageField(upload_to='images/fund', verbose_name='تصویر فیش')),
            ],
            options={
                'verbose_name': 'تنخواه',
                'verbose_name_plural': 'تنخواه',
            },
        ),
        migrations.CreateModel(
            name='ReceivePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_pay', models.CharField(choices=[('rec', 'دریافت'), ('pay', 'پرداخت')], max_length=3, verbose_name='دریافت / پرداخت')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('regard_to', models.CharField(max_length=100, verbose_name='بابت')),
                ('date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('receipt_image', models.ImageField(upload_to='images/receive_pays', verbose_name='تصویر فیش')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_receive_pays', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_receive_pays', to='government_accounts.organization', verbose_name='طرف حساب دولتی')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_receive_pays', to='non_government_accounts.personnel', verbose_name='پرسنل')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_receive_pays', to='non_government_accounts.suppliers', verbose_name='تأمین کننده')),
            ],
            options={
                'verbose_name': 'دریافت و پرداخت',
                'verbose_name_plural': 'دریافت\u200cها و پرداخت\u200cها',
            },
        ),
    ]
