# Generated by Django 4.2.1 on 2023-07-07 11:41

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0003_fund_receivepay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='cash',
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/fund', verbose_name='تصویر فیش'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='cost_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ هزینه'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='cost_description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح هزینه'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/receive_pays', verbose_name='تصویر فیش پرداختی'),
        ),
    ]
