# Generated by Django 4.2.1 on 2023-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0004_remove_fund_cash_alter_fund_charge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='operation_type',
            field=models.CharField(choices=[('rem', 'برداشت'), ('set', 'واریز')], default='set', max_length=3, verbose_name='نوع عملیات'),
        ),
    ]
