# Generated by Django 4.2.1 on 2023-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0005_fund_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='operation_type',
            field=models.CharField(choices=[('rem', 'برداشت'), ('set', 'واریز')], max_length=3, verbose_name='نوع عملیات'),
        ),
    ]
