# Generated by Django 4.2.1 on 2024-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0005_alter_cashbox_removal_date_alter_cashbox_settle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='cheque_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cheques', verbose_name='تصویر چک'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/receive_pays', verbose_name='تصویر فیش'),
        ),
    ]
