# Generated by Django 4.2.1 on 2023-07-12 10:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0006_alter_fund_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='charge_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
