# Generated by Django 4.2.1 on 2023-07-17 10:18

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('non_government_accounts', '0011_rename_noticeconflictorders_conflictorders'),
        ('government_accounts', '0001_initial'),
        ('cheques_receive_pay', '0007_alter_fund_charge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='charge_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='charge_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/fund', verbose_name='تصویر فیش واریزی'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_receive_pays', to='non_government_accounts.contractors', verbose_name='پیمانکار'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_receive_pays', to='government_accounts.organization', verbose_name='طرف حساب دولتی'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_receive_pays', to='non_government_accounts.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='receivepay',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_receive_pays', to='non_government_accounts.suppliers', verbose_name='تأمین کننده'),
        ),
    ]
