# Generated by Django 4.2.1 on 2023-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0008_alter_fund_charge_amount_alter_fund_charge_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('rem', 'برداشت'), ('set', 'واریز')], max_length=3, verbose_name='نوع عملیات')),
                ('settle_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی')),
                ('settle_image', models.ImageField(blank=True, null=True, upload_to='images/cash_box', verbose_name='تصویر فیش واریزی')),
                ('settle_description', models.TextField(blank=True, null=True, verbose_name='شرح واریز')),
                ('removal_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ برداشت')),
                ('removal_image', models.ImageField(blank=True, null=True, upload_to='images/cash_box', verbose_name='تصویر فیش برداشت')),
                ('removal_description', models.TextField(blank=True, null=True, verbose_name='شرح برداشت')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق',
            },
        ),
    ]
