# Generated by Django 4.2.1 on 2023-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_receive_pay', '0010_alter_cashbox_removal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='removal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cash_box/removal_images', verbose_name='تصویر فیش برداشت'),
        ),
    ]
