# Generated by Django 4.2.1 on 2023-10-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('cheques_receive_pay', '0012_receivepay_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivepay',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_receive_pays', to='projects.project', verbose_name='پروژه'),
        ),
    ]
