# Generated by Django 4.2.1 on 2023-08-01 07:30

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_costs_sketch_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrelated_to_project', models.TextField(blank=True, null=True, verbose_name='غیرمرتبط با پروژه\u200cها')),
                ('contract_type', models.CharField(choices=[('buy', 'خرید'), ('sal', 'فروش'), ('exc', 'معاوضه')], max_length=3, verbose_name='نوع قرارداد')),
                ('contract_title', models.CharField(max_length=250, verbose_name='عنوان قرارداد')),
                ('contract_party', models.CharField(max_length=250, verbose_name='طرف قرارداد')),
                ('contract_image', models.ImageField(upload_to='images/contract_images', verbose_name='تصویر قرارداد')),
                ('contract_date', django_jalali.db.models.jDateField(verbose_name='تاریخ قرارداد')),
                ('related_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_projects', to='projects.project', verbose_name='مرتبط با پروژه\u200cها')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
    ]
