# Generated by Django 4.2.1 on 2023-11-04 04:12

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('non_government_accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('owd', 'سند مالکیت'), ('atd', 'سند وکالت'), ('sic', 'گواهی امضاء'), ('unl', 'تعهدنامه')], max_length=3, verbose_name='نوع سند')),
                ('doc_image', models.ImageField(upload_to='images/registered_doc_images', verbose_name='تصویر سند')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_doc_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'سند ثبتی',
                'verbose_name_plural': 'اسناد ثبتی',
            },
        ),
        migrations.CreateModel(
            name='Proceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('proceeding_type', models.CharField(choices=[('del', 'تحویل'), ('oth', 'متفرقه')], max_length=3, verbose_name='نوع صورت جلسه')),
                ('proceeding_image', models.ImageField(upload_to='images/proceeding_image', verbose_name='تصویر صورت جلسه')),
                ('proceeding_date', django_jalali.db.models.jDateField(verbose_name='تاریخ صورت جلسه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceeding_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'صورت جلسه',
                'verbose_name_plural': 'صورت جلسه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OfficialDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('let', 'نامه'), ('lic', 'پروانه'), ('crt', 'گواهی')], max_length=3, verbose_name='نوع سند')),
                ('letter_type', models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع نامه')),
                ('license_type', models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع پروانه')),
                ('doc_title', models.CharField(max_length=250, verbose_name='عنوان سند')),
                ('doc_image', models.ImageField(upload_to='images/official_doc_images', verbose_name='تصویر سند')),
                ('send_receive_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ارسال / دریافت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_docs_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'سند اداری',
                'verbose_name_plural': 'اسناد اداری',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrelated_to_project', models.TextField(blank=True, null=True, verbose_name='غیرمرتبط با پروژه\u200cها')),
                ('contract_type', models.CharField(choices=[('buy', 'خرید'), ('sal', 'فروش'), ('rnt', 'اجاره'), ('exc', 'معاوضه')], max_length=3, verbose_name='نوع قرارداد')),
                ('contract_title', models.CharField(max_length=250, verbose_name='عنوان قرارداد')),
                ('contract_party', models.CharField(max_length=250, verbose_name='طرف قرارداد')),
                ('contract_image', models.ImageField(upload_to='images/contract_images', verbose_name='تصویر قرارداد')),
                ('contract_date', django_jalali.db.models.jDateField(verbose_name='تاریخ قرارداد')),
                ('related_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_projects', to='projects.project', verbose_name='مرتبط با پروژه\u200cها')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.CreateModel(
            name='ConditionStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن')], max_length=3, verbose_name='واحد کار')),
                ('requested_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ درخواستی پیمانکار')),
                ('confirmed_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تأییدشده سرپرست کارگاه')),
                ('accounting_confirm', models.CharField(choices=[('con', 'تأیید شده'), ('nco', 'تأیید نشده'), ('awc', 'در انتظار تأیید')], default='awc', max_length=3, verbose_name='وضعیت تأیید حسابداری')),
                ('management_confirm', models.CharField(choices=[('con', 'تأیید شده'), ('nco', 'تأیید نشده'), ('awc', 'در انتظار تأیید')], default='awc', max_length=3, verbose_name='وضعیت تأیید مدیریت')),
                ('final_deposit_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی نهایی')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_statement_contractors', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_statement_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'صورت وضعیت',
                'verbose_name_plural': 'صورت وضعیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BankReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_or_pay', models.CharField(choices=[('rec', 'دریافت'), ('pay', 'پرداخت')], max_length=3, verbose_name='دریافت / پرداخت')),
                ('receipt_date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('receipt_image', models.ImageField(upload_to='images/receipt_images', verbose_name='تصویر رسید بانکی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipt_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'رسید بانکی',
                'verbose_name_plural': 'رسیدهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('agreement_image', models.ImageField(upload_to='images/agreement_images', verbose_name='تصویر توافق\u200cنامه')),
                ('agreement_date', django_jalali.db.models.jDateField(verbose_name='تاریخ توافق\u200cنامه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'توافق\u200cنامه',
                'verbose_name_plural': 'توافق\u200cنامه\u200cها',
            },
        ),
    ]
