# Generated by Django 4.2.1 on 2023-08-01 09:08

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_costs_sketch_map'),
        ('projects_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('proceeding_type', models.CharField(choices=[('del', 'تحویل'), ('oth', 'متفرقه')], max_length=3, verbose_name='نوع صورت جلسه')),
                ('proceeding_image', models.ImageField(upload_to='images/proceeding_image', verbose_name='تصویر صورت جلسه')),
                ('proceeding_date', django_jalali.db.models.jDateField(verbose_name='تاریخ صورت جلسه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceeding_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'صورت جلسه',
                'verbose_name_plural': 'صورت جلسه\u200cها',
            },
        ),
    ]
