# Generated by Django 4.2.1 on 2023-11-26 11:05

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agreements',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bankreceipts',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bankreceipts',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conditionstatements',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conditionstatements',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contracts',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contracts',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officialdocs',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officialdocs',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registereddocs',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registereddocs',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
