# Generated by Django 4.2.1 on 2023-08-01 09:45

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('projects_docs', '0002_proceedings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_party', models.CharField(max_length=250, verbose_name='طرف حساب')),
                ('agreement_image', models.ImageField(upload_to='images/agreement_images')),
                ('agreement_date', django_jalali.db.models.jDateField(verbose_name='تاریخ توافق\u200cنامه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'توافق\u200cنامه',
                'verbose_name_plural': 'توافق\u200cنامه\u200cها',
            },
        ),
    ]
