# Generated by Django 4.2.1 on 2024-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_docs', '0003_alter_agreements_create_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='agreement_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/agreement_images', verbose_name='تصویر توافق\u200cنامه'),
        ),
        migrations.AlterField(
            model_name='bankreceipts',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/receipt_images', verbose_name='تصویر رسید بانکی'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/contract_images', verbose_name='تصویر قرارداد'),
        ),
        migrations.AlterField(
            model_name='officialdocs',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/official_doc_images', verbose_name='تصویر سند'),
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='proceeding_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/proceeding_image', verbose_name='تصویر صورت جلسه'),
        ),
        migrations.AlterField(
            model_name='registereddocs',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/registered_doc_images', verbose_name='تصویر سند'),
        ),
    ]
