# Generated by Django 4.2.1 on 2023-08-01 09:59

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('projects_docs', '0003_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='agreement_image',
            field=models.ImageField(upload_to='images/agreement_images', verbose_name='تصویر توافق\u200cنامه'),
        ),
        migrations.CreateModel(
            name='BankReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_or_pay', models.CharField(choices=[], max_length=3, verbose_name='دریافت / پرداخت')),
                ('receipt_date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('receipt_image', models.ImageField(upload_to='images/receipt_images', verbose_name='تصویر رسید بانکی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipt_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'رسید بانکی',
                'verbose_name_plural': 'رسیدهای بانکی',
            },
        ),
    ]
