# Generated by Django 4.2.1 on 2023-08-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('non_government_accounts', '0012_alter_orders_supplier'),
        ('projects_docs', '0004_alter_agreements_agreement_image_bankreceipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit', models.CharField(choices=[('sqm', 'مترمربع'), ('mel', 'مترطول'), ('kgm', 'کیلوگرم'), ('ton', 'تن')], max_length=3, verbose_name='واحد کار')),
                ('requested_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ درخواستی')),
                ('confirmed_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تایید شده')),
                ('accounting_confirm', models.CharField(choices=[('con', 'تأیید شده'), ('nco', 'تأیید نشده'), ('awc', 'در انتظار تأیید')], default='awc', max_length=3, verbose_name='وضعیت تأیید حسابداری')),
                ('management_confirm', models.CharField(choices=[('con', 'تأیید شده'), ('nco', 'تأیید نشده'), ('awc', 'در انتظار تأیید')], default='awc', max_length=3, verbose_name='وضعیت تأیید مدیریت')),
                ('final_deposit_amount', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ واریزی نهایی')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_statement_contractors', to='non_government_accounts.contractors', verbose_name='پیمانکار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_statement_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'صورت وضعیت',
                'verbose_name_plural': 'صورت وضعیت\u200cها',
            },
        ),
    ]
