# Generated by Django 4.2.1 on 2023-08-01 14:27

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_owners_birth_certificate_image_and_more'),
        ('projects_docs', '0006_registereddocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddocs',
            name='doc_image',
            field=models.ImageField(upload_to='images/registered_doc_images', verbose_name='تصویر سند'),
        ),
        migrations.CreateModel(
            name='OfficialDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('let', 'نامه'), ('lic', 'پروانه'), ('crt', 'گواهی')], max_length=3, verbose_name='نوع سند')),
                ('letter_type', models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع سند')),
                ('license_type', models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع سند')),
                ('doc_title', models.CharField(max_length=250, verbose_name='عنوان سند')),
                ('doc_image', models.ImageField(upload_to='images/official_doc_images', verbose_name='تصویر سند')),
                ('send_receive_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ارسال / دریافت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_docs_projects', to='projects.project', verbose_name='پروژه\u200c')),
            ],
            options={
                'verbose_name': 'سند اداری',
                'verbose_name_plural': 'اسناد اداری',
            },
        ),
    ]
