# Generated by Django 4.2.1 on 2023-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_docs', '0007_alter_registereddocs_doc_image_officialdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sal', 'فروش'), ('rnt', 'اجاره'), ('exc', 'معاوضه')], max_length=3, verbose_name='نوع قرارداد'),
        ),
    ]
