# Generated by Django 4.2.1 on 2023-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_docs', '0008_alter_contracts_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreceipts',
            name='receive_or_pay',
            field=models.CharField(choices=[('rec', 'دریافت'), ('pay', 'پرداخت')], max_length=3, verbose_name='دریافت / پرداخت'),
        ),
        migrations.AlterField(
            model_name='conditionstatements',
            name='confirmed_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ تأییدشده سرپرست کارگاه'),
        ),
        migrations.AlterField(
            model_name='conditionstatements',
            name='requested_amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ درخواستی پیمانکار'),
        ),
        migrations.AlterField(
            model_name='officialdocs',
            name='letter_type',
            field=models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='officialdocs',
            name='license_type',
            field=models.CharField(blank=True, choices=[('snd', 'ارسالی'), ('rec', 'دریافتی')], max_length=3, null=True, verbose_name='نوع پروانه'),
        ),
    ]
