# Generated by Django 4.2.1 on 2023-12-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع پیام')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('send_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ارسال')),
                ('seen', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_users', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200c کننده پیام')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_users', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده پیام')),
            ],
        ),
    ]
