# Generated by Django 4.2.1 on 2024-11-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع پیام')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('archive_sender', models.BooleanField(default=False)),
                ('archive_receiver', models.BooleanField(default=False)),
                ('visible_sender', models.BooleanField(default=True)),
                ('visible_receiver', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_users', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200c کننده پیام')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_users', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده پیام')),
            ],
            options={
                'permissions': (('write_message', 'نوشتن پیام'), ('seen_message', 'مشاهده پیام')),
            },
        ),
    ]
