# Generated by Django 4.2.1 on 2023-12-06 10:45

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_alter_message_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
