# Generated by Django 4.2.1 on 2023-12-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_alter_message_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible_receiver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_sender',
            field=models.BooleanField(default=True),
        ),
    ]
