# Generated by Django 4.2.1 on 2023-12-08 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_message_visible_receiver_message_visible_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_date',
        ),
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
