# Generated by Django 4.2.1 on 2023-12-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0006_alter_message_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='trash',
        ),
        migrations.AddField(
            model_name='message',
            name='archive_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='archive_sender',
            field=models.BooleanField(default=False),
        ),
    ]
