# Generated by Django 4.2.1 on 2023-05-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, verbose_name='نام ارگان')),
            ],
        ),
        migrations.AlterField(
            model_name='receive',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_accounts.organization', verbose_name='ارگان'),
        ),
    ]
