# Generated by Django 4.2.1 on 2023-11-11 17:06

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ و ساعت دریافت'),
        ),
    ]
