# Generated by Django 4.2.1 on 2023-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='receive_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ دریافتی'),
        ),
    ]
