# Generated by Django 4.2.1 on 2023-11-11 17:20

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0002_alter_receive_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receive',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ دریافت'),
        ),
    ]
