# Generated by Django 4.2.1 on 2023-05-07 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
# import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_contract_type'),
        ('government_accounts', '0002_organization_alter_receive_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(max_length=250, verbose_name='پرداخت بابت')),
                ('payment_amount', models.BigIntegerField(default=0, verbose_name='مبلغ پرداختی')),
                # ('payment_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_accounts.organization', verbose_name='ارگان')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_payments', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
