# Generated by Django 4.2.1 on 2023-06-03 16:21

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0002_alter_payment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت دریافت'),
        ),
    ]
