# Generated by Django 4.2.1 on 2023-06-08 10:10

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0003_alter_receive_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت پرداخت'),
        ),
    ]
