# Generated by Django 4.2.1 on 2023-05-07 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
# import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_contract_type'),
        ('government_accounts', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=150, verbose_name='نوع فعالیت')),
                # ('activity_date', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فعالیت')),
                ('activity_result', models.CharField(choices=[('fn', 'پایان یافته'), ('do', 'در حال انجام')], max_length=2, verbose_name='نتیجه فعالیت')),
                ('activity_descriptions', models.TextField(verbose_name='توضیحات فعالیت در حال انجام')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_accounts.organization', verbose_name='ارگان')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_activities', to='projects.project', verbose_name='پروژه')),
            ],
        ),
    ]
