# Generated by Django 4.2.1 on 2023-11-11 17:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0003_receive_create_record_receive_update_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receive',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
