# Generated by Django 4.2.1 on 2023-11-13 17:44

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0004_alter_receive_create_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='create_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='update_record',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ فعالیت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت'),
        ),
    ]
