# Generated by Django 4.2.1 on 2023-06-08 10:58

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0004_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت فعالیت'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فعالیت در حال انجام'),
        ),
    ]
