# Generated by Django 4.2.1 on 2023-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0004_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'ارگان', 'verbose_name_plural': 'ارگان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='receive',
            options={'verbose_name': 'دریافت', 'verbose_name_plural': 'دریافت\u200cها'},
        ),
    ]
