# Generated by Django 4.2.1 on 2023-06-12 16:08

from django.db import migrations, models
import government_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0007_alter_activity_activity_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='pdf',
            field=models.FileField(blank=True, upload_to=government_accounts.models.pdf_upload_path),
        ),
    ]
