# Generated by Django 4.2.1 on 2023-05-08 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('government_accounts', '0007_alter_activity_activity_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت دریافت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت دریافت'),
        ),
        migrations.AlterField(
            model_name='receive',
            name='receive_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت دریافت'),
        ),
    ]
